---
- name: 'Install OS dependencies'
  apt:
    state: latest
    name: "{{ db_packages }}"
  become: yes

- name: 'Create MySQL database'
  mysql_db:
    name: "{{ wp_db_name }}"        
    login_user: root
    state: present

- name: 'Create database user with name and password with all database privileges'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{ wp_user_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ wp_host_ip }}"

- name: 'Configure MySQL to accept remote connections'
  copy:
    src: './files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify:
    - Restart mysql